sonar.projectKey=portable-runtime
sonar.organization=metratio
sonar.projectName=portable-runtime
sonar.projectVersion=1.0
sonar.sources=src/portable_runtime
sonar.tests=tests
sonar.python.version=3.12
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.venv/**,**/.pytest_cache/**,**/.mypy_cache/**,**/data/**,**/__pycache__/**,**/htmlcov/**
sonar.coverage.exclusions=tests/**
sonar.python.coverage.reportPaths=coverage.xml
sonar.test.inclusions=tests/**
sonar.qualitygate.wait=false


